### ISSUE TITLE
Checklist to going live

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#35]
This is our checklist to complete before the first version of the supplementary style guide can go live.

### Guide updates

- [x] Add entry for replaceable values (PR #30)
- [x] Add entry for formatting code examples (#38)
- [x] Add entry for long code blocks in procedures (#39)
- [x] Add entry for lead-in sentence for Prereqs and Procedure headings (PR #37)
- [x] Remove empty placeholders (PR #36)
- [x] Edit the guide (@leswilliams44, @jhoyt-rh, others?)
- [x] Remove WIP note in guide - wait until we're closer to releasing before doing this.

### Glossary deprecation updates

_See glossary deprecation plan for details_

- [x] Redirect old glossary doc (GitHub) to new guide (https://github.com/redhat-documentation/glossary-of-terms-and-conventions-for-product-documentation/pull/11)
- [x] Update glossary GitHub repo README to note deprecation and link to new guide 
- [x] Contact tooling team for how to redirect or add a deprecation note to glossary on GitLab (Jira opened with tooling team, PR opened in the meantime to add a warning)
- [x] Update Mojo/the Source pages

### Communicate new guide availability

- [x] Once live, communicate out through email lists and meetings!

**Comment by bergerhoffer** [comment]
Need to merge these PRs:

* https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation/-/merge_requests/209 (adding deprecation note to GitLab glossary)
* https://github.com/redhat-documentation/glossary-of-terms-and-conventions-for-product-documentation/pull/11 (redirecting GitHub glossary to style guide)

**Comment by stoobie** [comment]
@bergerhoffer It appears that these have both been merged, correct?

**Comment by bergerhoffer** [comment]
Closing this as the style guide is now officially live! :tada:

**Comment by stoobie** [comment]
@bergerhoffer @cbudz Woohoo!
